### ISSUE TITLE
connecting to cluster using lb (and without) fails

### ISSUE THREAD

**Issue by ranlandau** [johnwlockwood/txnats#31]
Unhandled Error
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Anaconda2\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Anaconda2\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Anaconda2\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Anaconda2\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Anaconda2\lib\site-packages\twisted\internet\tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "C:\Anaconda2\lib\site-packages\twisted\internet\tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Anaconda2\lib\site-packages\twisted\internet\endpoints.py", line 116, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "C:\Anaconda2\lib\site-packages\txnats\protocol.py", line 243, in dataReceived
    self.server_settings = ServerInfo(**settings)
exceptions.TypeError: __init__() got an unexpected keyword argument 'connect_urls'

**Comment by espectro** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/internet/kqreactor.py", line 293, in _doWriteOrRead
    why = selectable.doRead()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 125, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/txnats-0.7.5-py3.5.egg/txnats/protocol.py", line 242, in dataReceived

builtins.TypeError: __init__() got an unexpected keyword argument 'connect_urls'
